settings:
  config:
    # With this enabled anyone set as op has full permissions when managing GroupManager
    # The user will be able to promote players to the same group or even above.
    opOverrides: true
    
    # Default setting for 'mantogglevalidate'
    # true will cause GroupManager to attempt name matching by default.
    validate_toggle: true
    # ************************************************************************************************************************************************************
    # *** NOTE: Having this feature enabled can allow improper use of Command Blocks which may lead to undesireable permission changes. You have been warned! ***
    # ************************************************************************************************************************************************************
    allow_commandblocks: false
  data:
    save:
      minutes: 10
      hours: 24
  logging:
    level: INFO
  mirrors:
    world:
      world nether
      - groups
      - usres
      flatroom
      - groups
      - users
      end of world
      - groups
      - users
      Pvp
      - groups
      - users
      End
      - groups
      - users
      ClanWars
      - groups
      - users
      AriesCraft
      - groups
      - users
      
        
