settings:
  config:
    # With this enabled anyone set as op has full permissions when managing GroupManager
    # The user will be able to promote players to the same group or even above.
    opOverrides: true
    
    # Default setting for 'mantogglevalidate'
    # true will cause GroupManager to attempt name matching by default.
    validate_toggle: true
    # ************************************************************************************************************************************************************
    # *** NOTE: Having this feature enabled can allow improper use of Command Blocks which may lead to undesireable permission changes. You have been warned! ***
    # ************************************************************************************************************************************************************
    allow_commandblocks: false
  data:
    save:
      minutes: 10
      hours: 24
  logging:
    level: INFO
  mirrors:
        # Worlds listed here have their settings mirrored in their children.
        # The first element 'world' is the main worlds name, and is the parent world.
        # subsequent elements 'world_nether' and 'world_the_end' are worlds which will use
        # the same user/groups files as the parent.
        # the element 'all_unnamed_worlds' specifies all worlds that aren't listed, and automatically mirrors them to it's parent.
        # Each child world can be configured to mirror the 'groups', 'users' or both files from its parent.
    world:
      world nether
      - groups
      - usres
      flatroom
      - groups
      - users
      end of world
      - groups
      - users
      Pvp
      - groups
      - users
      End
      - groups
      - users
      ClanWars
      - groups
      - users
      AriesCraft
      - groups
      - users
        #  world2:      (World2 would have it's own set of user and groups files)
        #    world3:
        #    - users    (World3 would use the users.yml from world2, but it's own groups.yml)
        #    world4:
        #    - groups   (World4 would use the groups.yml from world2, but it's own users.yml)
        #  world5:
        #    - world6   (this would cause world6 to mirror both files from world5)

      
        
